const oflineData = [
    {
        id:1,
        name:"Google",
        email:"google@world.com",
        status:"active",
        gender:"male"
    },
    {
        id:2,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"female"
    },
    {
        id:3,
        name:"Google",
        email:"google@world.com",
        status:"active",
        gender:"female"
    },
    {
        id:4,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"male"
    },
    {
        id:5,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"female"
    },
    {
        id:6,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"male"
    },
    {
        id:7,
        name:"Google",
        email:"google@world.com",
        status:"active",
        gender:"female"
    },
    {
        id:8,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"male"
    },
    {
        id:9,
        name:"Google",
        email:"google@world.com",
        status:"inactive",
        gender:"female"
    },
    {
        id:10,
        name:"Google",
        email:"google@world.com",
        status:"active",
        gender:"male"
    },
]

export default oflineData